repos:
  # Shared pre-commit
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]

  # Client Pre-commit
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        name: client-prettier
        files: ^client/src/.*\.(ts|tsx|js|css|html|json)$
        args:
          [
            "--config=./client/.prettierrc",
            "--ignore-path=./client/.prettierignore",
          ]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.33.0"
    hooks:
      - id: eslint
        name: client-eslint
        additional_dependencies:
          - eslint
          - eslint-config-react-app
          - typescript
          - "@typescript-eslint/parser"
          - "@typescript-eslint/eslint-plugin"
          - eslint-config-prettier
          - eslint-plugin-jsx-a11y
          - eslint-plugin-prettier
          - eslint-plugin-react
          - eslint-plugin-react-hooks
        files: ^client/src/.*\.[jt]sx?$
        types: [file]
        args:
          [
            "--config=./client/.eslintrc.js",
            "--ignore-path=./client/.eslintignore",
          ]
  # Server Pre-commit
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        name: server-prettier
        files: ^server/src/.*\.(ts|tsx|js|css|html|json)$
        args:
          [
            "--config=./server/.prettierrc",
            "--ignore-path=./server/.prettierignore",
          ]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.33.0"
    hooks:
      - id: eslint
        name: server-eslint
        additional_dependencies:
          - eslint
          - typescript
          - "@typescript-eslint/parser"
          - "@typescript-eslint/eslint-plugin"
          - eslint-config-prettier
          - eslint-plugin-prettier
        files: ^server/src/.*\.[jt]sx?$
        types: [file]
        args: ["--config=./server/.eslintrc.js"]
